//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DesignArk.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_SMARTCOLOUR_TYPES           107
#define IDD_SMARTCOLOUR_OPS             108
#define IDD_SMARTCOLOUR_BUILTIN         109
#define IDD_SMARTCOLOUR_OTHER           110
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DesignArkTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_CARET                       310
#define IDB_PNG1                        329
#define IDB_ARROW_RIGHT_HOVER           334
#define IDB_BITMAP1                     336
#define IDB_ARROW_RIGHT_CLICK           336
#define IDD_APP_ABOUT                   343
#define IDC_MFCVSLISTBOX_TYPES          1051
#define IDC_SPLIT1                      1052
#define IDC_COMBO_COLOUR_TYPES          1053
#define IDC_MFCVSLISTBOX_OPS            1064
#define IDC_COMBO_COLOUR_OPS            1065
#define IDC_MFCVSLISTBOX_BUILTIN_CLASSES 1066
#define IDC_SMARTCOLOUR_OTHERS_NUMBERS_COLOUR 1066
#define IDC_MFCVSLISTBOX_OPS2           1066
#define IDC_MFCVSLISTBOX_BUILTIN_FUNCTIONS 1067
#define IDC_COMBO_COLOUR_OPS2           1067
#define IDC_SMARTCOLOUR_OTHERS_NUMBERS_COLOUR2 1067
#define IDC_COMBO_COLOUR_BUILTIN_FUNCTIONS 1068
#define IDC_COMBO_COLOUR_BUILTIN_CLASSES 1069
#define IDC_SMARTCOLOUR_OTHERS_COMMENT_COMBO 1070
#define IDC_SMARTCOLOUR_OTHERS_COMMENT_COMBO2 1071
#define IDC_SMARTCOLOUR_OTHERS_FONT     1071
#define IDC_SMARTCOLOUR_OTHER_COMMENTS_COLOUR 1074
#define IDC_SMARTCOLOR_OTHER_INDENT     1083
#define ID_VIEW_SMARTCOLOURWINDOW       32771
#define ID_VIEW_                        32772
#define ID_HELP_OPENWEBSITE             32773
#define ID_HELP_VIEWUSERDOCSONLINE      32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        345
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
